name: Test and release

on:
  workflow_call:
    secrets:
      TOKEN_TO_RUN_GITHUB_ACTION:
        required: true

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    needs: test
    uses: ./.github/workflows/build.yaml
    secrets: inherit
