name: Test and release

on:
  workflow_call:
    inputs:
      skip_test:
        description: 'Skip test'
        required: false
        type: boolean
    secrets:
      TOKEN_TO_RUN_GITHUB_ACTION:
        required: true

jobs:
  test:
    if: !${{ inputs.skip_test }}
    uses: ./.github/workflows/test.yaml

  build:
    needs: test
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  trigger-pigeon:
    needs: build
    uses: ./.github/workflows/trigger-pigeon-app.yaml
    secrets: inherit
