name: Trigger pigeon app CI/CD

on:
  workflow_call:
    secrets:
      TOKEN_TO_RUN_GITHUB_ACTION:
        required: true

jobs:
  trigger-pigeon-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Pigeon App Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN_TO_RUN_GITHUB_ACTION }}
          repository: kneu-messenger-pigeon/pigeon-app@main
          event-type: built_${{ github.event.repository.name }}
